theme: jekyll-theme-slate

title: Data Science Consulting
description: Franziska Horn

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - Impressum.md
